language: ruby
rvm:
- 2.0.0
env:
- DB=sqlite
before_script:
- "bundle exec rake db:create:all"
- "bundle exec rake db:migrate"
- "bundle exec rake db:populate"
- "bundle exec rake db:test:prepare"
script:
- "bundle exec rake db:test:prepare"
- "bundle exec rake rspec --trace"